# mk.help.mk — shared `help` target text for Bmake It roles
# Included at the end of workspace / framework / prog / lib makefiles.
# @impl 0f87-6a98-7829-4019

.if !defined(_MK_HELP_MK_)
_MK_HELP_MK_ = 1

# BMK_HELP_ROLE is set by the including role file before .include
.if !defined(BMK_HELP_ROLE)
BMK_HELP_ROLE = workspace
.endif

help:
	@echo "Bmake It — BSD-make build system (role: ${BMK_HELP_ROLE})"
	@echo ""
	@echo "Current selection"
	@echo "  OS_ARCH=${OS_ARCH}"
	@echo "  TARGET=${TARGET}  TARGET_ARCH=${TARGET_ARCH}  TOOLCHAIN=${TOOLCHAIN}"
	@echo "  BMK_MKDIR=${BMK_MKDIR}"
	@echo "  BUILD_ROOT=${BUILD_ROOT}"
	@echo ""
	@echo "================================================================"
	@echo "TARGETS"
	@echo "================================================================"
.if ${BMK_HELP_ROLE} == "workspace"
	@echo "  all (default)  Build every framework in PREREQS order, then"
	@echo "                 aggregate bin/lib/share into workspace build/"
	@echo "  clean          Source-only slate: remove all build/, distrib/,"
	@echo "                 .gen-*.mk, .depend under the workspace"
	@echo "  install        Copy pre-built build/<KEY>/{bin,lib,share} into"
	@echo "                 DESTDIR+PREFIX (does NOT build first)"
	@echo "  add-parent     Append WS=<abs-path> to PARENT_WS= in makefile"
	@echo "  help           This message"
	@echo ""
	@echo "  (packaging targets pkg/deb/rpm/msi/port — deferred)"
.elif ${BMK_HELP_ROLE} == "framework"
	@echo "  all (default)  Build modules in LIBS= order, copy-up artifacts"
	@echo "  clean          Remove framework+module build/ and .gen-*.mk"
	@echo "  copy-up        Build (if needed) and copy outputs to workspace"
	@echo "  help           This message"
.elif ${BMK_HELP_ROLE} == "prog"
	@echo "  all (default)  Compile+link executable into build/<KEY>/bin/"
	@echo "  clean          Remove module build/ and stray objects"
	@echo "  copy-up        Build and copy binary to framework build/<KEY>/bin/"
	@echo "  help           This message"
.elif ${BMK_HELP_ROLE} == "lib"
	@echo "  all (default)  Compile+link library into build/<KEY>/lib/"
	@echo "  clean          Remove module build/ and stray objects/libs"
	@echo "  copy-up        Build and copy libs to framework build/<KEY>/lib/"
	@echo "  help           This message"
.endif
	@echo ""
	@echo "================================================================"
	@echo "VARIABLES (command line or makefile)"
	@echo "================================================================"
	@echo "  TARGET=        OS label. Default: host OS."
	@echo "                 Examples: macos  freebsd  linux"
	@echo "  TARGET_ARCH=   CPU arch. Default: host arch."
	@echo "                 Examples: arm64  amd64"
	@echo "  TOOLCHAIN=     Compiler bundle. Default: llvm"
	@echo "                 Values: llvm | gcc"
	@echo "  ABI=           Optional ABI/libc when non-default"
	@echo "                 linux: glibc (default, omitted) | musl"
	@echo "                 win:   msvc (default, omitted) | mingw | cygwin"
	@echo ""
	@echo "  Together these form OS_ARCH = <os>-<arch>[-toolchain][-abi]"
	@echo "  Defaults are omitted from the key (llvm not shown, etc.)."
	@echo ""
	@echo "  BMK_MKDIR=    Absolute path to the Bmake It mk/ directory"
	@echo "  MAKESYSPATH=   bmake system include path; include mk/ and"
	@echo "                 platform share/mk, e.g.:"
	@echo "                   \$$BMK_MKDIR:/opt/local/share/mk   (MacPorts)"
	@echo "                   \$$BMK_MKDIR:/usr/share/mk         (Linux/FreeBSD)"
	@echo ""
	@echo "  DEBUG_FLAGS=   e.g. -g  (native BSD make variable)"
	@echo "  CFLAGS+=       Extra C flags (append with += in makefile)"
	@echo "  CXXFLAGS+=     Extra C++ flags"
	@echo "  LDFLAGS+=      Extra link flags"
	@echo "  YFLAGS+= LFLAGS+=   lex/yacc flags"
	@echo ""
	@echo "  DESTDIR=       Install staging root (install target)"
	@echo "  PREFIX=        Final install prefix (default /usr/local)"
	@echo ""
.if ${BMK_HELP_ROLE} == "workspace"
	@echo "Workspace makefile macros"
	@echo "  PARENT_WS=     Space-separated absolute paths to parent workspaces"
.elif ${BMK_HELP_ROLE} == "framework"
	@echo "Framework makefile macros"
	@echo "  PREREQS=       REQUIRED even when empty. Ordered list of"
	@echo "                 frameworks whose public headers/libs are visible"
.elif ${BMK_HELP_ROLE} == "prog"
	@echo "Executable module macros"
	@echo "  PROG=          Binary name (default: module dir without .m)"
	@echo "  LIBS=          Libraries to link (-l); link-time only, no headers"
	@echo "  SRCS=          Source list (default: auto-scan src/)"
.elif ${BMK_HELP_ROLE} == "lib"
	@echo "Library module macros"
	@echo "  LIB=           Base name (default: dir without .m / leading lib)"
	@echo "  LIB_SHARED=    YES (default) shared | NO static archive only"
	@echo "  SHLIB_MAJOR=   Shared lib major version (default 1 if shared)"
	@echo "  SHLIB_MINOR=   Optional minor version"
	@echo "  LIBS=          Link-time library deps"
	@echo "  INCL=          Generated headers to promote to framework public"
	@echo "  SRCS=          Source list (default: auto-scan src/)"
.endif
	@echo ""
	@echo "================================================================"
	@echo "EXAMPLES"
	@echo "================================================================"
	@echo "  bmake"
	@echo "  bmake TARGET=freebsd TARGET_ARCH=amd64"
	@echo "  bmake TOOLCHAIN=gcc"
	@echo "  bmake TARGET=macos TARGET_ARCH=arm64 TOOLCHAIN=gcc"
	@echo "  bmake clean"
	@echo "  bmake install DESTDIR=/tmp/stage PREFIX=/opt/demo"
.if ${BMK_HELP_ROLE} == "workspace"
	@echo "  bmake add-parent WS=/abs/path/to/other-workspace"
.endif
	@echo ""
	@echo "  export BMK_MKDIR=/path/to/bmk/mk"
	@echo "  export MAKESYSPATH=\$$BMK_MKDIR:/opt/local/share/mk"
	@echo "  bmake"
	@echo ""
	@echo "See also: README.md and the design docs (00-overview … 50-macros)."

.PHONY: help

.endif # _MK_HELP_MK_
