#!/bin/sh
# gen-mod-order.sh — prototype for mk.framework.mk's dependency resolution.
#
# Scans the current directory for *.m module subdirectories, queries each
# one's LIBS= (module names it depends on, per REQ-libs-macro-link-only-
# headers-via-prereqs-req) via `bmake -f <dir>/makefile -V LIBS`, builds a
# dependency graph, and emits a topologically-sorted SUBDIR= list to a
# generated .mk fragment (mirroring the .depend-style caching approach in
# REQ-prereqs-resolution-cached-like-depend-req).
#
# Exits non-zero with a diagnostic on a detected cycle (real design says
# "no cycle detection is required" per REQ-prereqs-misorder-no-validation-req,
# but a topological sort implementation naturally detects unsortable cycles
# as a side effect - this prototype reports it rather than looping forever,
# without claiming that constitutes designed cycle-detection UX).

set -eu

OUT="${1:-.gen-mod-order.mk}"

# Discover *.m module directories (REQ-modules-and-frameworks-auto-discovered-req)
mods=""
for d in *.m; do
    [ -d "$d" ] || continue
    name="${d%.m}"
    mods="$mods $name"
done

if [ -z "$mods" ]; then
    echo "SUBDIR=" > "$OUT"
    exit 0
fi

# Build dependency map: dep_<name> = space-separated LIBS= entries
tmpdir=$(mktemp -d)
trap 'rm -rf "$tmpdir"' EXIT

for name in $mods; do
    libs=$(bmake -f "${name}.m/makefile" -V LIBS 2>/dev/null || true)
    echo "$libs" > "$tmpdir/dep_${name}"
done

# Kahn's algorithm, implemented with plain POSIX shell + temp files
# (a real implementation would likely use awk for speed; shell is fine
# for a prototype and for small module counts in practice).
remaining="$mods"
sorted=""
progress=1

while [ -n "$remaining" ] && [ "$progress" = "1" ]; do
    progress=0
    still_remaining=""
    for name in $remaining; do
        deps=$(cat "$tmpdir/dep_${name}")
        ready=1
        for dep in $deps; do
            # dep is "ready" only if it's already sorted (or not one of
            # our own modules at all - e.g. a prereq-framework library,
            # which is out of scope for THIS graph and assumed available)
            case " $mods " in
                *" $dep "*)
                    case " $sorted " in
                        *" $dep "*) : ;;  # already satisfied
                        *) ready=0 ;;
                    esac
                    ;;
                *) : ;;  # not one of our modules, ignore for this graph
            esac
        done
        if [ "$ready" = "1" ]; then
            sorted="$sorted $name"
            progress=1
        else
            still_remaining="$still_remaining $name"
        fi
    done
    remaining="$still_remaining"
done

if [ -n "$remaining" ]; then
    echo "gen-mod-order.sh: dependency cycle detected among:$remaining" >&2
    exit 1
fi

{
    echo "# generated by gen-mod-order.sh - do not edit by hand"
    printf 'SUBDIR='
    for name in $sorted; do
        printf ' %s.m' "$name"
    done
    printf '\n'
} > "$OUT"

echo "Wrote $OUT:"
cat "$OUT"
