#!/bin/sh
# @impl 0f87-6a98-5f76-2a44
# REQ-nested-invocation-reentrancy-guard-req: BMAKE must be an absolute path
# before any nested invocation -- a bare name can resolve back to a wrapper
# of this same script's caller (or, worse, to itself), causing unbounded
# self-recursion. The output file is written via a temp-file-then-rename so a
# concurrent or nested invocation of this same directory's discovery never
# observes a half-written or momentarily-deleted cache.
set -eu
OUT="${1:-.gen-mod-order.mk}"
BMAKE="${BMAKE:-bmake}"
case "$BMAKE" in
    /*) ;;
    *)
        _resolved=$(command -v "$BMAKE" 2>/dev/null || true)
        [ -n "$_resolved" ] && BMAKE="$_resolved"
        ;;
esac

_bmake_q() {
    _mf=$1
    _var=$2
    if [ -n "${BMK_MKDIR:-}" ]; then
        _sys="${BMK_SYS_MK:-}"
        if [ -z "$_sys" ]; then
            for d in /opt/local/share/mk /usr/share/mk /usr/local/share/mk; do
                if [ -f "$d/sys.mk" ]; then _sys=$d; break; fi
            done
        fi
        if [ -n "$_sys" ]; then
            env -u MAKEFLAGS -u MAKELEVEL -u MFLAGS \
                MAKESYSPATH="${BMK_MKDIR}:${_sys}" \
                BMK_MKDIR="$BMK_MKDIR" \
                "$BMAKE" -m "$BMK_MKDIR" -m "$_sys" \
                BMK_MKDIR="$BMK_MKDIR" \
                -f "$_mf" -V "$_var" 2>/dev/null || true
        else
            env -u MAKEFLAGS -u MAKELEVEL -u MFLAGS \
                MAKESYSPATH="$BMK_MKDIR" \
                BMK_MKDIR="$BMK_MKDIR" \
                "$BMAKE" -m "$BMK_MKDIR" \
                BMK_MKDIR="$BMK_MKDIR" \
                -f "$_mf" -V "$_var" 2>/dev/null || true
        fi
    else
        env -u MAKEFLAGS -u MAKELEVEL -u MFLAGS \
            "$BMAKE" -f "$_mf" -V "$_var" 2>/dev/null || true
    fi
}

mods=""
for d in *.m; do
    [ -d "$d" ] || continue
    name="${d%.m}"
    mods="$mods $name"
done

if [ -z "$mods" ]; then
    echo "MODULE_SUBDIR=" > "$OUT.tmp.$$"
    mv -f "$OUT.tmp.$$" "$OUT"
    exit 0
fi

tmpdir=$(mktemp -d)
trap 'rm -rf "$tmpdir"' EXIT

for name in $mods; do
    libs=$(_bmake_q "${name}.m/makefile" LIBS)
    libid=$(_bmake_q "${name}.m/makefile" LIB)
    progid=$(_bmake_q "${name}.m/makefile" PROG)
    ids="$name"
    [ -n "$libid" ] && ids="$ids $libid lib${libid}"
    [ -n "$progid" ] && ids="$ids $progid"
    if [ -n "${BMK_DEBUG:-}" ]; then
        echo "gen-mod-order: $name LIBS=[$libs] LIB=[$libid] PROG=[$progid]" >&2
    fi
    echo "$libs" > "$tmpdir/dep_${name}"
    echo "$ids" > "$tmpdir/ids_${name}"
done

is_satisfied() {
    dep="$1"
    for s in $sorted; do
        for id in $(cat "$tmpdir/ids_${s}"); do
            [ "$id" = "$dep" ] && return 0
        done
    done
    return 1
}

is_local() {
    dep="$1"
    for m in $mods; do
        for id in $(cat "$tmpdir/ids_${m}"); do
            [ "$id" = "$dep" ] && return 0
        done
    done
    return 1
}

remaining="$mods"
sorted=""
progress=1

while [ -n "$remaining" ] && [ "$progress" = "1" ]; do
    progress=0
    still_remaining=""
    for name in $remaining; do
        deps=$(cat "$tmpdir/dep_${name}")
        ready=1
        for dep in $deps; do
            if is_local "$dep"; then
                if ! is_satisfied "$dep"; then
                    ready=0
                fi
            fi
        done
        if [ "$ready" = "1" ]; then
            sorted="$sorted $name"
            progress=1
        else
            still_remaining="$still_remaining $name"
        fi
    done
    remaining="$still_remaining"
done

if [ -n "$remaining" ]; then
    echo "gen-mod-order.sh: dependency cycle detected among:$remaining" >&2
    exit 1
fi

{
    echo "# generated by gen-mod-order.sh — do not edit"
    printf 'MODULE_SUBDIR='
    for name in $sorted; do
        printf ' %s.m' "$name"
    done
    printf '\n'
    echo "# order:$sorted"
} > "$OUT.tmp.$$"
mv -f "$OUT.tmp.$$" "$OUT"
