#!/bin/sh
# gen-fw-order.sh — topological order of frameworks from PREREQS=
# Writes SUBDIR=... to the given output file
#
# @impl 0f87-6a98-5f76-2a44
# REQ-nested-invocation-reentrancy-guard-req: BMAKE must be an absolute path
# before any nested invocation, and the output file is written via
# temp-file-then-rename -- see gen-mod-order.sh for why.

set -eu

OUT="${1:-.gen-fw-order.mk}"
BMAKE="${BMAKE:-bmake}"
case "$BMAKE" in
    /*) ;;
    *)
        _resolved=$(command -v "$BMAKE" 2>/dev/null || true)
        [ -n "$_resolved" ] && BMAKE="$_resolved"
        ;;
esac

fws=""
for d in */; do
    [ -d "$d" ] || continue
    name="${d%/}"
    case "$name" in
        build|distrib) continue ;;
    esac
    if [ -f "$name/makefile" ] && grep -q '^PREREQS' "$name/makefile" 2>/dev/null; then
        fws="$fws $name"
    fi
done

if [ -z "$fws" ]; then
    echo "FRAMEWORK_SUBDIR=" > "$OUT.tmp.$$"
    mv -f "$OUT.tmp.$$" "$OUT"
    exit 0
fi

tmpdir=$(mktemp -d)
trap 'rm -rf "$tmpdir"' EXIT

for name in $fws; do
    prereqs=$($BMAKE -f "$name/makefile" -V PREREQS 2>/dev/null || true)
    echo "$prereqs" > "$tmpdir/dep_${name}"
done

remaining="$fws"
sorted=""
progress=1

while [ -n "$remaining" ] && [ "$progress" = "1" ]; do
    progress=0
    still_remaining=""
    for name in $remaining; do
        deps=$(cat "$tmpdir/dep_${name}")
        ready=1
        for dep in $deps; do
            case " $fws " in
                *" $dep "*)
                    case " $sorted " in
                        *" $dep "*) : ;;
                        *) ready=0 ;;
                    esac
                    ;;
                *) : ;; # external parent-workspace framework
            esac
        done
        if [ "$ready" = "1" ]; then
            sorted="$sorted $name"
            progress=1
        else
            still_remaining="$still_remaining $name"
        fi
    done
    remaining="$still_remaining"
done

if [ -n "$remaining" ]; then
    echo "gen-fw-order.sh: dependency cycle detected among:$remaining" >&2
    exit 1
fi

{
    echo "# generated by gen-fw-order.sh — do not edit"
    printf 'FRAMEWORK_SUBDIR='
    for name in $sorted; do
        printf ' %s' "$name"
    done
    printf '\n'
} > "$OUT.tmp.$$"
mv -f "$OUT.tmp.$$" "$OUT"

echo "Wrote $OUT: $(cat "$OUT")"
